name: Solarcord Automatic Release

on:
    push:
        branches:
            - main
    workflow_dispatch:

env:
    FORCE_COLOR: true
    USERNAME: GitHub-Actions

permissions:
    contents: write

jobs:
    Build:
        name: Build and Release Solarcord
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3

            - name: Use Node.js 24
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build web
              run: pnpm buildWebStandalone

            - name: Build
              run: pnpm buildStandalone

            - name: Generate plugin lists
              run: |
                  pnpm generatePluginJson dist/plugins.json
                  pnpm generateEquicordPluginJson dist/equicordplugins.json
                  pnpm generateVencordPluginJson dist/vencordplugins.json
                  pnpm generateDevsList dist/devs.json

            - name: Collect files to be released
              run: |
                  cd dist
                  mkdir release

                  cp browser/browser.* release 2>/dev/null || true
                  cp Equicord.user.{js,js.LEGAL.txt} release 2>/dev/null || true

                  # Copia i plugin json, gli zip delle estensioni e i file asar
                  cp *.{json,zip,asar} release 2>/dev/null || true

                  # Copia eventuali file desktop
                  cp desktop/* release 2>/dev/null || true
                  for file in equibop/*; do
                    if [ -f "$file" ]; then
                      filename=$(basename "$file")
                      cp "$file" "release/equibop${filename^}"
                    fi
                  done

                  find release -size 0 -delete
                  rm -f release/package.json
                  rm -f release/*.map

            # Pacchettizza la build in uno ZIP pronto per Linux/Desktop
            - name: Create Linux Zip Bundle
              run: |
                  cd dist/release
                  zip -r ../../solarcord-build-linux.zip ./*

            - name: Upload to GitHub Releases
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: "latest"
                  name: "Solarcord Nightly Build"
                  body: "Build automatica aggiornata all'ultimo commit di `main`."
                  files: |
                      solarcord-build-linux.zip
                      dist/release/*
                  overwrite: true
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
